### ISSUE TITLE
ResearchKit  for proposed Clinical Trial 

### ISSUE THREAD

**Issue by kevlicht** [ResearchKit/mPower#3]
Please advise if this is the appropriate avenue to inquire how to go about developing an app. for a clinical trial I plan on conducting later this year and if so what type of descriptions and specifications are welcome/required. Thanks. Kevin

**Comment by jwe-apple** [comment]
Hi Kevin, please contact researchkit@apple.com

**Comment by kevlicht** [comment]
Thank you jwe-apple. ResearchKit gave me a response that lead me to you, see below. I am interested in contacting someone to help me. Kevin

`<snip>`

**Comment by DanKeen** [comment]
Removing private email and locking - Kevin, please drop another email to researchkit@apple.com, we'll follow up there.
